name: PostgreSQL tests
on: [ push ]

jobs:
  Test-postgres-integration:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Attempt to fix 509 issue pt 1
        run: go env -w GOPROXY=direct

      - name: Attempt to fix 509 issue pt 2
        run: apk add --no-cache git

      - name: Attempt to fix 509 issue pt 3
        run: apk --no-cache add ca-certificates

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          LIBSCHEMA_POSTGRES_TEST_DSN: "postgres://postgres:postgres@postgres"
        run: go test -v lspostgres/...

