name: PostgreSQL tests
on: push

jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        env: LIBSCHEMA_POSTGRES_TEST_DSN="postgres://postgres:postgres@postgres
        run: go test -v lspostgres/...

